GET http://localhost:5000/games
### 
GET http://localhost:5000/games?pageNumber=2
###
GET http://localhost:5000/games/1

###
GET http://localhost:5000/games/2

###
GET http://localhost:5000/games/4

###
POST http://localhost:5000/games
Content-Type: application/json

{
    "name": "Forza Horizon 6",
    "genreId": 3,
    "price": 59.99,
    "releaseDate": "2023-10-20"
}

###
POST http://localhost:5000/games
Content-Type: application/json

{
    "name": "Street Fighter",
    "genreId": 1,
    "price": 19.99,
    "releaseDate": "2021-12-12"
}

###
PUT http://localhost:5000/games/1
Content-Type: application/json

{
    "name": "RE:Village",
    "genreId": 3,
    "price": 19.99,
    "releaseDate": "2021-12-12"
}

###
DELETE http://localhost:5000/games/7

###
GET http://localhost:5000/genres

### 1. registration of a new user
POST http://localhost:5000/auth/register
Content-Type: application/json

{
  "username": "admin1",
  "password": "SuperSecret12322!"
}

### 2. Login with the new user to get a token
POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "username": "admin1",
  "password": "SuperSecret12322!"
}

### 3. try to create a game without a token (should return 401 Unauthorized)
POST http://localhost:5000/games
Content-Type: application/json

{
  "name": "Test Game",
  "genreId": 1,
  "price": 10.0,
  "releaseDate": "2024-01-01"
}

### 4. create a game with a token (should return 200 OK)
POST http://localhost:5000/games
Content-Type: application/json
Authorization: Bearer {token}

{
  "name": "Test Game",
  "genreId": 1,
  "price": 10.0,
  "releaseDate": "2024-01-01"
}

### 1. user registration
POST http://localhost:5000/auth/register
Content-Type: application/json

{
  "username": "user1",
  "password": "User123!"
}

### 2. user login to get a token
POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "username": "user1",
  "password": "User123!"
}

### 3. try to delete a game with a user token (should return 403 Forbidden)
DELETE http://localhost:5000/games/2
Authorization: Bearer {token}

### 4. make user admin (should return 200 OK)
POST http://localhost:5000/auth/make-admin
Content-Type: application/json

{
  "username": "user1"
}

### 5. login after making user admin to get a new token (should return 200 OK)
POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "username": "user1",
  "password": "User123!"
}

### 6. delete a game with the new admin token (should return 200 OK)
DELETE http://localhost:5000/games/14
Authorization: Bearer {token}

### 1. get all games(id sorted by default)
GET http://localhost:5000/games

### 2. sort by price (from cheap to expensive)
GET http://localhost:5000/games?sortBy=price&sortOrder=asc

### 3. sort by price (from expensive to cheap)
GET http://localhost:5000/games?sortBy=price&sortOrder=desc

### 4. sort by name (from A to Z)
GET http://localhost:5000/games?sortBy=name&sortOrder=asc

### 5. sort by release date (newest first)
GET http://localhost:5000/games?sortBy=releaseDate&sortOrder=desc&pageNumber=4&pageSize=10

### 6. filter by genre (e.g., Fighting - genreId=1)
GET http://localhost:5000/games?genreId=1

### 7. filter by price (from 20 to 50)
GET http://localhost:5000/games?minPrice=20&maxPrice=50

### 8. search by name (contains "Forza")
GET http://localhost:5000/games?search=Forza
### 10. search + sort + pagination
GET http://localhost:5000/games?search=Street&sortBy=price&sortOrder=asc&pageNumber=1&pageSize=3


### 1. valid review creation (should return 200 OK)
POST http://localhost:5000/games/16/reviews
Content-Type: application/json
Authorization: Bearer {token}

{
  "rating": 5,
  "comment": "nice game, good graphics!"
}

### 2. invalid rating (should return 400)
POST http://localhost:5000/games/12/reviews
Content-Type: application/json
Authorization: Bearer {token}  

{
  "rating": 10,
  "comment": "nice game, good graphics!"
}

### 3. empty comment (should return 400)
POST http://localhost:5000/games/1/reviews
Content-Type: application/json
Authorization: Bearer {token}

{
  "rating": 4,
  "comment": ""
}

### 4. too short comment (should return 400)
POST http://localhost:5000/games/1/reviews
Content-Type: application/json
Authorization: Bearer {token}

{
  "rating": 4,
  "comment": "Too short"
}

### 1. create a review for a game
POST http://localhost:5000/games/18/reviews
Content-Type: application/json
Authorization: Bearer {token}
{
  "rating": 4,
  "comment": "Good game, but has some bugs."
}

### 2. update the review
PUT http://localhost:5000/games/16/reviews/1
Content-Type: application/json
Authorization: Bearer {token}
{
  "rating": 5,
  "comment": "Excellent game, bugs fixed in the patch!"
}

### 3. try to update someone else's review (should return 403 Forbidden)
PUT http://localhost:5000/games/16/reviews/2
Content-Type: application/json
Authorization: Bearer {token}

{
  "rating": 1,
  "comment": "Poor game!"
}

### 4. delete the review
DELETE http://localhost:5000/games/16/reviews/2
Authorization: Bearer {token}
PUT http://localhost:5000/games/1/reviews/999
Content-Type: application/json
Authorization: Bearer {token}

{
  "rating": 3,
  "comment": "Test non-existent review."
}

### 6. validation: rating out of range (should return 400)
PUT http://localhost:5000/games/1/reviews/1
Content-Type: application/json
Authorization: Bearer {token}

{
  "rating": 10,
  "comment": "Invalid rating."
}