GET http://localhost:5000/games
### 
GET http://localhost:5000/games?pageNumber=2
###
GET http://localhost:5000/games/1

###
GET http://localhost:5000/games/2

###
GET http://localhost:5000/games/4

###
POST http://localhost:5000/games
Content-Type: application/json

{
    "name": "Forza Horizon 6",
    "genreId": 3,
    "price": 59.99,
    "releaseDate": "2023-10-20"
}

###
POST http://localhost:5000/games
Content-Type: application/json

{
    "name": "Street Fighter",
    "genreId": 1,
    "price": 19.99,
    "releaseDate": "2021-12-12"
}

###
PUT http://localhost:5000/games/1
Content-Type: application/json

{
    "name": "RE:Village",
    "genreId": 3,
    "price": 19.99,
    "releaseDate": "2021-12-12"
}

###
DELETE http://localhost:5000/games/7

###
GET http://localhost:5000/genres